### ISSUE TITLE
Missing support for Cocoapods installation

### ISSUE THREAD

**Issue by jomnius** [electrode-io/react-native-electrode-bridge#25]
BUG: please add support to install "react native elecrode bridge" framework via Cocoapods

Readme at iOS chapter says "install ElectrodeReactNativeBridge as dependency through your preferred way". One very popular way is to use [Cocoapods](https://cocoapods.org), since it's easy, works today, is pretty reliable and gives consistent results. Everything else requires more manual works and is more error prone.

I couldn't find "ElectrodeReactNativeBridge" or anything like it from Cocoapods, maybe I just couldn't guess the right name? Please document the correct framework name in readme.

However you have removed required podspec file at PR "ios:removed unused podspec #10", so I wonder if you have no plans to support Cocoapods for some reason?

**Comment by jomnius** [comment]
Can be closed.

**Comment by adamski** [comment]
Why was this PR issue closed, I need to be able to install via Cocoapods also.

**Comment by samridhgupta** [comment]
Having troubles on adding this bridge lib to my existing ios app
Can somebody help me with right steps to add the dependency manually to the existing ios project?
