### ISSUE TITLE
docs: difference between event handler registration methods

### ISSUE THREAD

**Issue by cdaringe** [electrode-io/react-native-electrode-bridge#52]
# problem

there are two types event handler registration methods:

- https://github.com/electrode-io/react-native-electrode-bridge#electrodebridgeregisterrequesthandler, and
- https://github.com/electrode-io/react-native-electrode-bridge#electrodebridgeregistereventlistener

after digesting the readme, i'm not clear when i should use one or the other.  is there guidance w.r.t. this?  i spend a minute looking at the source, and it seems they each care about a specific type of message, as seen here: https://github.com/electrode-io/react-native-electrode-bridge/blob/master/js/ElectrodeBridge.js#L221

# discussion

thanks for the docs!  sorry if i missed something glaring :)

**Comment by belemaire** [comment]
@cdaringe 
Looks like the README was missing some documentation around message types. 
Created https://github.com/electrode-io/react-native-electrode-bridge/pull/53 to add [missing section](https://github.com/electrode-io/react-native-electrode-bridge/pull/53/files) to documentation.

Please refer to this section as it might hopefully answer your question.

**Comment by cdaringe** [comment]
thanks!  looks great!  closed by #53
